# Generated by Django 5.0.6 on 2024-06-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_location', models.CharField(blank=True, max_length=100)),
                ('destination_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_location', models.CharField(blank=True, max_length=100)),
                ('travel_mode', models.CharField(blank=True, max_length=50)),
                ('is_highway', models.BooleanField(default=False)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('travel_time', models.TimeField(blank=True, null=True)),
                ('travel_instructions', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
