# Generated by Django 5.0.6 on 2024-06-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='travel_instructions',
            field=models.CharField(blank=True, max_length=1255),
        ),
    ]
