# Generated by Django 5.0.6 on 2024-06-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TR', '0002_alter_form_travel_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.CharField(blank=True, max_length=100)),
                ('start_location', models.CharField(blank=True, max_length=100)),
                ('destination_location', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
